export const VAT_RATE = 0.15;

export const STORE_INFO = {
  name: "SmartPOS Retail",
  nameAr: "سمارت بوس للتجزئة",
  crNumber: "1234567890",
  vatNumber: "300012345600003",
  address: "Riyadh, Saudi Arabia",
  addressAr: "الرياض، المملكة العربية السعودية",
  phone: "+966 50 000 0000",
  thankYou: "Thank you for shopping with us!",
  thankYouAr: "شكراً لتسوقكم معنا!",
};

export const CATEGORIES = [
  "All",
  "Grocery",
  "Beverages",
  "Snacks",
  "Electronics",
  "Household",
  "Personal Care"
];

export const TRANSLATIONS = {
  en: {
    dashboard: "Dashboard",
    pos: "POS",
    inventory: "Inventory",
    reports: "Reports",
    settings: "Settings",
    logout: "Logout",
    todaySales: "Today's Sales",
    totalOrders: "Total Orders",
    lowStock: "Low Stock Items",
    searchProducts: "Search products...",
    categories: "Categories",
    cart: "Cart",
    subtotal: "Subtotal",
    vat: "VAT (15%)",
    total: "Total",
    checkout: "Checkout",
    cash: "Cash",
    card: "Card",
    print: "Print Receipt",
    addProduct: "Add Product",
    editProduct: "Edit Product",
    delete: "Delete",
    save: "Save",
    cancel: "Cancel",
    name: "Name",
    price: "Price",
    stock: "Stock",
    sku: "SKU",
    barcode: "Barcode",
    category: "Category",
    costPrice: "Cost Price",
    imageUrl: "Image URL",
    emptyCart: "Your cart is empty",
    paymentSuccess: "Payment Successful!",
    stockUpdated: "Stock updated successfully",
    lowStockAlert: "Low stock alert!",
    admin: "Admin",
    cashier: "Cashier",
    login: "Login",
    email: "Email",
    password: "Password",
  },
  ar: {
    dashboard: "لوحة التحكم",
    pos: "نقطة البيع",
    inventory: "المخزون",
    reports: "التقارير",
    settings: "الإعدادات",
    logout: "تسجيل الخروج",
    todaySales: "مبيعات اليوم",
    totalOrders: "إجمالي الطلبات",
    lowStock: "أصناف منخفضة المخزون",
    searchProducts: "البحث عن المنتجات...",
    categories: "الفئات",
    cart: "السلة",
    subtotal: "المجموع الفرعي",
    vat: "ضريبة القيمة المضافة (15%)",
    total: "الإجمالي",
    checkout: "الدفع",
    cash: "نقداً",
    card: "بطاقة",
    print: "طباعة الإيصال",
    addProduct: "إضافة منتج",
    editProduct: "تعديل منتج",
    delete: "حذف",
    save: "حفظ",
    cancel: "إلغاء",
    name: "الاسم",
    price: "السعر",
    stock: "المخزون",
    sku: "رمز المنتج",
    barcode: "الباركود",
    category: "الفئة",
    costPrice: "سعر التكلفة",
    imageUrl: "رابط الصورة",
    emptyCart: "السلة فارغة",
    paymentSuccess: "تمت عملية الدفع بنجاح!",
    stockUpdated: "تم تحديث المخزون بنجاح",
    lowStockAlert: "تنبيه انخفاض المخزون!",
    admin: "مدير",
    cashier: "كاشير",
    login: "تسجيل الدخول",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
  }
};
