export const VAT_RATE = 0.15;

export const STORE_INFO = {
  name: "SmartPOS Retail",
  nameAr: "سمارت بوس للتجزئة",
  crNumber: "1234567890",
  vatNumber: "300012345600003",
  address: "Riyadh, Saudi Arabia",
  addressAr: "الرياض، المملكة العربية السعودية",
  phone: "+966 50 000 0000",
  thankYou: "Thank you for shopping with us!",
  thankYouAr: "شكراً لتسوقكم معنا!",
};

export const CATEGORIES = [
  "All",
  "Grocery",
  "Beverages",
  "Snacks",
  "Electronics",
  "Household",
  "Personal Care"
];

export const TRANSLATIONS = {
  en: {
    dashboard: "Dashboard",
    pos: "POS",
    inventory: "Inventory",
    reports: "Reports",
    settings: "Settings",
    logout: "Logout",
    todaySales: "Today's Sales",
    weeklySales: "Weekly Sales",
    monthlySales: "Monthly Sales",
    yearlySales: "Yearly Sales",
    totalOrders: "Total Orders",
    lowStock: "Low Stock Items",
    searchProducts: "Search products...",
    categories: "Categories",
    cart: "Cart",
    vat: "VAT (15%)",
    total: "Total",
    checkout: "Checkout",
    print: "Print Receipt",
    addProduct: "Add Product",
    editProduct: "Edit Product",
    delete: "Delete",
    save: "Save",
    cancel: "Cancel",
    name: "Name",
    price: "Price",
    stock: "Stock",
    sku: "SKU",
    barcode: "Barcode",
    category: "Category",
    costPrice: "Cost Price",
    emptyCart: "Your cart is empty",
    paymentSuccess: "Payment Successful!",
    stockUpdated: "Stock updated successfully",
    lowStockAlert: "Low stock alert!",
    admin: "Admin",
    cashier: "Cashier",
    login: "Login",
    email: "Email",
    password: "Password",
    storeSettings: "Store Settings",
    shopNameEn: "Shop Name (English)",
    shopNameAr: "Shop Name (Arabic)",
    addressEn: "Address (English)",
    addressAr: "Address (Arabic)",
    crNumber: "CR Number",
    vatNumber: "VAT Number",
    phone: "Phone",
    thankYouEn: "Thank You Message (English)",
    thankYouAr: "Thank You Message (Arabic)",
    manageCategories: "Manage Categories",
    addCategory: "Add Category",
    editCategory: "Edit Category",
    categoryNameEn: "Category Name (English)",
    categoryNameAr: "Category Name (Arabic)",
    recentSales: "Recent Sales",
    viewAll: "View All",
    allStocked: "All products are well stocked",
    barcodeMode: "Barcode Mode",
    addCustomer: "Add Customer",
    currentOrder: "Current Order",
    quantity: "Quantity",
    unitPrice: "Unit Price",
    subtotal: "Subtotal",
    tax: "Tax",
    payableAmount: "Payable Amount",
    cash: "Cash",
    card: "Card",
    split: "Split",
    cashAmount: "Cash Amount",
    cardAmount: "Card Amount",
    discount: "Discount",
    percentage: "Percentage",
    fixed: "Fixed Amount",
    apply: "Apply",
    holdOrder: "Hold Order",
    proceed: "Proceed",
    viewCart: "View Cart",
    deleteProductConfirm: "Delete Product?",
    deleteProductDesc: "Are you sure you want to delete this product? This action cannot be undone.",
    noBarcode: "No barcode",
    settingsSaved: "Settings saved successfully!",
    deleteCategoryConfirm: "Are you sure you want to delete this category?",
    brandingInfo: "Branding & Common Information",
    logoText: "Logo Text",
    logoUrl: "Logo Image URL",
    logoPreview: "Logo Preview",
  },
  ar: {
    dashboard: "لوحة التحكم",
    pos: "نقطة البيع",
    inventory: "المخزون",
    reports: "التقارير",
    settings: "الإعدادات",
    logout: "تسجيل الخروج",
    todaySales: "مبيعات اليوم",
    weeklySales: "مبيعات الأسبوع",
    monthlySales: "مبيعات الشهر",
    yearlySales: "مبيعات السنة",
    totalOrders: "إجمالي الطلبات",
    lowStock: "أصناف منخفضة المخزون",
    searchProducts: "البحث عن المنتجات...",
    categories: "الفئات",
    cart: "السلة",
    vat: "ضريبة القيمة المضافة (15%)",
    total: "الإجمالي",
    checkout: "الدفع",
    print: "طباعة الإيصال",
    addProduct: "إضافة منتج",
    editProduct: "تعديل منتج",
    delete: "حذف",
    save: "حفظ",
    cancel: "إلغاء",
    name: "الاسم",
    price: "السعر",
    stock: "المخزون",
    sku: "رمز المنتج",
    barcode: "الباركود",
    category: "الفئة",
    costPrice: "سعر التكلفة",
    emptyCart: "السلة فارغة",
    paymentSuccess: "تمت عملية الدفع بنجاح!",
    stockUpdated: "تم تحديث المخزون بنجاح",
    lowStockAlert: "تنبيه انخفاض المخزون!",
    admin: "مدير",
    cashier: "كاشير",
    login: "تسجيل الدخول",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    storeSettings: "إعدادات المتجر",
    shopNameEn: "اسم المتجر (إنجليزي)",
    shopNameAr: "اسم المتجر (عربي)",
    addressEn: "العنوان (إنجليزي)",
    addressAr: "العنوان (عربي)",
    crNumber: "رقم السجل التجاري",
    vatNumber: "الرقم الضريبي",
    phone: "رقم الهاتف",
    thankYouEn: "رسالة شكر (إنجليزي)",
    thankYouAr: "رسالة شكر (عربي)",
    manageCategories: "إدارة الفئات",
    addCategory: "إضافة فئة",
    editCategory: "تعديل فئة",
    categoryNameEn: "اسم الفئة (إنجليزي)",
    categoryNameAr: "اسم الفئة (عربي)",
    recentSales: "المبيعات الأخيرة",
    viewAll: "عرض الكل",
    allStocked: "جميع المنتجات متوفرة بشكل جيد",
    barcodeMode: "وضع الباركود",
    addCustomer: "إضافة عميل",
    currentOrder: "الطلب الحالي",
    quantity: "الكمية",
    unitPrice: "سعر الوحدة",
    subtotal: "المجموع الفرعي",
    tax: "الضريبة",
    payableAmount: "المبلغ المستحق",
    cash: "نقداً",
    card: "بطاقة",
    split: "مقسم",
    cashAmount: "المبلغ النقدي",
    cardAmount: "مبلغ البطاقة",
    discount: "خصم",
    percentage: "نسبة مئوية",
    fixed: "مبلغ ثابت",
    apply: "تطبيق",
    holdOrder: "تعليق الطلب",
    proceed: "إتمام العملية",
    viewCart: "عرض السلة",
    deleteProductConfirm: "حذف المنتج؟",
    deleteProductDesc: "هل أنت متأكد أنك تريد حذف هذا المنتج؟ لا يمكن التراجع عن هذا الإجراء.",
    noBarcode: "لا يوجد باركود",
    settingsSaved: "تم حفظ الإعدادات بنجاح!",
    deleteCategoryConfirm: "هل أنت متأكد أنك تريد حذف هذه الفئة؟",
    brandingInfo: "العلامة التجارية والمعلومات العامة",
    logoText: "نص الشعار",
    logoUrl: "رابط صورة الشعار",
    logoPreview: "معاينة الشعار",
  }
};
